### PR TITLE
Pass --console-address to both standalone and distributed modes

### PR DESCRIPTION
**Pull request by sergeyshaykhullin**
**Description of the change**

Always pass --console-address to minio

**Benefits**
From 8.0.0 minio helm-chart in distributed mode is not operational.
All nodes use dynamic console ports, but container port is always 9001.
Minio console used for liveness/readiness probes and can't find any service on 9001 port.

**Possible drawbacks**
I don't know does this change will be enough to fix minio distributed setup

**Applicable issues**
Related to: https://github.com/bitnami/bitnami-docker-minio/issues/22

**Additional information**

Next steps - bump minio image version for helm-chart: https://github.com/bitnami/charts/tree/master/bitnami/minio

### CODE REVIEW

**Comment by sergeyshaykhullin** [comment]
@marcosbc Done

**Review by migruiz4 — CHANGES_REQUESTED** [review]
Hi @sergeyshaykhullin!

Thank you very much for reporting the issue and submitting the fix, but there is a problem with the proposed solution.

The fix should be like this:
```bash
ARGS=("server" "--certs-dir" "${MINIO_CERTSDIR}" "--console-address" ":${MINIO_CONSOLE_PORT_NUMBER}")
# Add any extra flags passed to this script
ARGS+=("$@")
if is_boolean_yes "$MINIO_DISTRIBUTED_MODE_ENABLED"; then
    read -r -a nodes <<< "$(tr ',;' ' ' <<< "${MINIO_DISTRIBUTED_NODES}")"
    for node in "${nodes[@]}"; do
        if is_distributed_ellipses_syntax; then
            ARGS+=("${MINIO_SCHEME}://${node}")
        else
            ARGS+=("${MINIO_SCHEME}://${node}:${MINIO_API_PORT_NUMBER}/${MINIO_DATADIR}")
        fi
    done
else
    ARGS+=("${MINIO_DATADIR}")
fi
```

Otherwise, the MINIO_DATADIR argument would fail when Distributed mode is enabled.

In addition, the same fix should be applied at https://github.com/bitnami/bitnami-docker-minio/blob/1faaa4d180d6f00d53319e8230271528eed14a0f/2021/debian-10/rootfs/opt/bitnami/scripts/libminio.sh#L137-L151

**Review by migruiz4 — APPROVED** [review]
Thank you @sergeyshaykhullin for applying the suggested changes, looks good to me!

**Comment by viceice** [comment]
Is there any workaround, I'm currently stuck in upgrade 😕

**Comment by viceice** [comment]
Workaround for helm chart **values.yaml**

```yaml
# override args
# https://github.com/bitnami/bitnami-docker-minio/pull/24
args:
  - "/opt/bitnami/scripts/minio/run.sh"
  - "--console-address"
  - ":9001"
```

**Pull request merged**
